### ISSUE TITLE
Can't comiple 

### ISSUE THREAD

**Issue by ajthemacboy** [Glitchfiend/BiomesOPlenty#468]
Hi! I'm having trouble compiling BOP on Ubuntu Linux with the Java 8 JDK.

Here's the log: http://paste.ubuntu.com/11062365/

I don't know how to interpret the stacktrace; it says this at one point:

`/home/aj/Desktop/BOP/BiomesOPlenty/build/sources/java/biomesoplenty/common/items/ItemJarFilled.java:129: error: ')' expected
						entityPlayer.setCurrentItemOrArmor(0, new ItemStack(BOPCItems.jarEmpty, 1, 0);`

Is this an issue with BOP or with my setup? Thanks for your help!

**Comment by Adaptivity** [comment]
Looks like @wwrpg broke something by this [commit](https://github.com/Glitchfiend/BiomesOPlenty/commit/9c2f8af89cd76e35349a09125caa84b1a2c534e8).

**Comment by Adaptivity** [comment]
I have an idea how to fix it. Hold on.

**Comment by fewizz** [comment]
replace with       
entityPlayer.setCurrentItemOrArmor(0, new ItemStack(BOPCItems.jarEmpty, 1, 0));

**Comment by Adaptivity** [comment]
I fixed it and another issue too. Just need to test :)

**Comment by fewizz** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/pull/469

**Comment by Adaptivity** [comment]
I said I'm fixed it :)

**Comment by fewizz** [comment]
ok =\

**Comment by ajthemacboy** [comment]
This is still happening when I run ./gradlew build:

'warning: [options] bootstrap class path not set in conjunction with -source 1.6
/home/aj/Desktop/BiomesOPlenty/build/sources/java/biomesoplenty/common/items/ItemJarFilled.java:129: error: ')' expected
						entityPlayer.setCurrentItemOrArmor(0, new ItemStack(BOPCItems.jarEmpty, 1, 0);'

**Comment by Adaptivity** [comment]
My PR not yet merged (and you can't fork it since I removed branch with the fix but it still can be merged). You have to wait.

**Comment by ajthemacboy** [comment]
Alright thanks. I saw that the repo had been updated today and just assumed it had been fixed.

**Comment by ajthemacboy** [comment]
Alright, I applied the fix myself, but now when I try to compile I get this error (the old one is gone):

`/home/aj/Desktop/BiomesOPlenty/build/sources/java/biomesoplenty/common/blocks/BlockBOPColorizedSapling.java:75: error: no suitable method found for canBlockStay(World,int,int,int,int)
        if (!this.canBlockStay(world, x, y, z, meta))`

**Comment by Adaptivity** [comment]
Change "canBlockStay" to "isValidPosition"

**Comment by Adaptivity** [comment]
New build is up here: http://files.minecraftforge.net/BiomesOPlenty/

**Comment by wwrpg** [comment]
Real sorry about that! I tested and compiled it fine on my computer... but then I failed to copy all the changes to github and typed in some of my changes by hand (forgetting the extra  ")").

**Comment by Adaptivity** [comment]
No worries. You made great bugfixes. Hope you'll fix some more bugs later.

**Comment by wwrpg** [comment]
I really love the mod, and how much it adds! And I since I know how to mod, I thought I might as well help contribute a little. From now on out I'll double check my changes in github compile before pulling a request.

**Comment by ajthemacboy** [comment]
By the way, do I need to run `gradlew setupDecompWorkspace` before I compile?
